# Generated by Django 4.2.6 on 2023-10-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Введите постоянную ссылку', max_length=255, unique=True, verbose_name='Постоянная ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование категории', max_length=255, unique=True, verbose_name='Наименование категории')),
                ('image', models.ImageField(help_text='Загрузите изображение категории', upload_to='category_img/%Y/%m/%d/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Введите постоянную ссылку', max_length=255, unique=True, verbose_name='Постоянная ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование подкатегории', max_length=255, unique=True, verbose_name='Наименование подкатегории')),
                ('image', models.ImageField(help_text='Загрузите изображение подкатегории', upload_to='subcategory_img/%Y/%m/%d/', verbose_name='Изображение подкатегории')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Введите постоянную ссылку', max_length=255, unique=True, verbose_name='Постоянная ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование продукта', max_length=255, unique=True, verbose_name='Наименование продукта')),
                ('image', models.ImageField(help_text='Загрузите изображение продукта', upload_to='product_img/%Y/%m/%d/', verbose_name='Изображение продукта')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, help_text='Введите описание продукта', verbose_name='Описание')),
                ('subcategory', models.ForeignKey(help_text='Выберите подкатегорию', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcategory', verbose_name='подкатегория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
