# Generated by Django 4.2.6 on 2023-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_id_2abda1_idx',
            old_fields=('id', 'slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение категории', upload_to='image/category_img/%Y/%m/%d/', verbose_name='Изображение категории'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
    ]
